version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: constructs
    versions:
    - 3.2.117
    - 3.3.11
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
  - dependency-name: "@testing-library/dom"
    versions:
    - 7.29.4
