name: Deploy

on:
  workflow_dispatch: {}
  push:
    branches: master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: install yarn
      run: npm install -g yarn
    - name: install dependencies
      run: yarn install
    - name: build
      run: npx lerna run build
    - name: synth
      run: |
        cd packages/catalog
        npx cdk synth
    - name: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        cd packages/catalog
        npx cdk deploy --require-approval=never construct-catalog-prod
